const specialties = [
    { specialty: 'Ginecólogo' },
    { specialty: 'Dermatólogo' },
    { specialty: 'Pediatra' },
    { specialty: 'Traumatólogo y Ortopedista' },
    { specialty: 'Gastroenterólogo' },
    { specialty: 'Cirujano general' },
    { specialty: 'Oftalmólogo' },
    { specialty: 'Psicólogo' },
    { specialty: 'Otorrino' },
    { specialty: 'Neurólogo' },
    { specialty: 'Urólogo' },
    { specialty: 'Endocrinólogo' },
    { specialty: 'Cardiólogo' },
    { specialty: 'Neurocirujano' },
    { specialty: 'Neumólogo' },
    { specialty: 'Internista' },
    { specialty: 'Médico general' },
    { specialty: 'Cirujano plástico' },
    { specialty: 'Reumatólogo' },
    { specialty: 'Dentista' },
    { specialty: 'Cirujano cardiovascular y torácico' },
    { specialty: 'Cirujano maxilofacial' },
    { specialty: 'Oncólogo' },
    { specialty: 'Nutricionista' },
    { specialty: 'Hematólogo' },
    { specialty: 'Nefrólogo' },
    { specialty: 'Geriatra' },
    { specialty: 'Especialista en Medicina Física y Rehabilitación' },
    { specialty: 'Radiólogo' },
    { specialty: 'Neonatólogo' },
    { specialty: 'Cirujano pediátrico' },
    { specialty: 'Infectólogo' },
    { specialty: 'Alergista' },
    { specialty: 'Neumólogo pediátrico' },
    { specialty: 'Anestesiólogo' },
    { specialty: 'Especialista en Medicina Intensiva' },
    { specialty: 'Especialista en Administración de Salud' },
    { specialty: 'Patólogo clínico' },
    { specialty: 'Patólogo' },
    { specialty: 'Especialista en Emergencias' },
    { specialty: 'Quiropráctico' },
    { specialty: 'Fisioterapeuta' },
    { specialty: 'Especialista en Medicina Estética' },
    { specialty: 'Médico familiar' },
    { specialty: 'Médico legal' },
    { specialty: 'Terapeuta complementario' },
    { specialty: 'Genetista' },
    { specialty: 'Neurofisiólogo clínico' },
    { specialty: 'Fonoaudiólogo' },
    { specialty: 'Cirujano vascular' },
    { specialty: 'Epidemiólogo' },
    { specialty: 'Homeópata' },
    { specialty: 'Especialista en Medicina Nuclear' },
    { specialty: 'Médico del Deporte' },
    { specialty: 'Especialista en Medicina Natural' },
    { specialty: 'Médico ocupacional' },
    { specialty: 'Médico del Trabajo' },
    { specialty: 'Técnico en Laboratorio Clínico' },
    { specialty: 'Especialista en Salud Pública' },
    { specialty: 'Bioquímico' },
    { specialty: 'Farmacólogo' },
    { specialty: 'Especialista en Radioterapia' },
    { specialty: 'Podólogo' },
    { specialty: 'Óptico' },
    { specialty: 'Enfermero' },
    { specialty: 'Cirujano oncólogo' }
]
  
module.exports = specialties;