const specialties = [
    'Ginecólogo',
    'Dermatólogo',
    'Pediatra',
    'Traumatólogo y Ortopedista',
    'Gastroenterólogo',
    'Cirujano general',
    'Oftalmólogo',
    'Psicólogo',
    'Otorrino',
    'Neurólogo',
    'Urólogo',
    'Endocrinólogo',
    'Cardiólogo',
    'Neurocirujano',
    'Neumólogo',
    'Internista',
    'Médico general',
    'Cirujano plástico',
    'Reumatólogo',
    'Dentista',
    'Cirujano cardiovascular y torácico',
    'Cirujano maxilofacial',
    'Oncólogo',
    'Nutricionista',
    'Hematólogo',
    'Nefrólogo',
    'Geriatra',
    'Especialista en Medicina Física y Rehabilitación',
    'Radiólogo',
    'Neonatólogo',
    'Cirujano pediátrico',
    'Infectólogo',
    'Alergista',
    'Neumólogo pediátrico',
    'Anestesiólogo',
    'Especialista en Medicina Intensiva',
    'Especialista en Administración de Salud',
    'Patólogo clínico',
    'Patólogo',
    'Especialista en Emergencias',
    'Quiropráctico',
    'Fisioterapeuta',
    'Especialista en Medicina Estética',
    'Médico familiar',
    'Médico legal',
    'Terapeuta complementario',
    'Genetista',
    'Neurofisiólogo clínico',
    'Fonoaudiólogo',
    'Cirujano vascular',
    'Epidemiólogo',
    'Homeópata',
    'Especialista en Medicina Nuclear',
    'Médico del Deporte',
    'Especialista en Medicina Natural',
    'Médico ocupacional',
    'Médico del Trabajo',
    'Técnico en Laboratorio Clínico',
    'Especialista en Salud Pública',
    'Bioquímico',
    'Farmacólogo',
    'Especialista en Radioterapia',
    'Podólogo',
    'Óptico',
    'Enfermero',
    'Cirujano oncólogo',
  ];

  module.exports = specialties;